version: '3'

services:
  controller:
    image: ngrinder/controller:latest
    ports:
      - "80:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    networks:
      ngrinder-test-net:
        ipv4_address: 172.240.0.1
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ~/ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent:latest
    links:
      - "controller:controller"
    networks:
      - ngrinder-test-net
    volumes:
      - ./agent_conf:/opt/ngrinder-agent/.ngrinder-agent/agent.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - controller
    deploy:
      mode: replicated
      replicas: 3

# port 9001
  simple-server:
    image: simple-server:latest
    networks:
      ngrinder-test-net:
        ipv4_address: 172.240.0.11
    environment:
      - TZ=Asia/Seoul

# port 9000
  simple-graalvm-server:
    image: simple-graalvm-server:latest
    networks:
      ngrinder-test-net:
        ipv4_address: 172.240.0.10
    environment:
      - TZ=Asia/Seoul

networks:
  ngrinder-test-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.240.0.0/16
          ip_range: 172.240.1.0/24